### ISSUE TITLE
开发环境下模块热替换功能？

### ISSUE THREAD

**Issue by cnloop** [JesseZhao1990/multipage-webpack-scaffolding#1]
```
new webpack.NamedModulesPlugin(),
new webpack.HotModuleReplacementPlugin()
```
即使在webpack.config.dev.js文件中补上这两行代码也没有用，怎么办呢？

**Comment by JesseZhao1990** [comment]
@cnloop 我刚刚试了一下，js可以热加载，修改html文件和css不能热加载。稍后抽空我定位一下问题，修复一下。

**Comment by JesseZhao1990** [comment]
开发环境支持css热加载。https://github.com/JesseZhao1990/multipage-webpack-scaffolding/commit/b3332c4b375b6e9825e1b175c1f193ecf5561e27
