### ISSUE TITLE
请问有没有静态资源的存放目录啊

### ISSUE THREAD

**Issue by tong822218** [JesseZhao1990/multipage-webpack-scaffolding#11]
我想把layui引入到项目中，但是用require的方式试了很多次有各种问题，我就想在html页面中直接引入layui的links和script，所以我在项目根目录下创建了static文件夹，把layui放到里面，然后再html中引入这个文件夹中的静态资源

但是页面报错如下：
Refused to apply style from 'http://localhost:8080/static/layui/css/layui.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by JesseZhao1990** [comment]
> 我想把layui引入到项目中，但是用require的方式试了很多次有各种问题，我就想在html页面中直接引入layui的links和script，所以我在项目根目录下创建了static文件夹，把layui放到里面，然后再html中引入这个文件夹中的静态资源
> 
> 但是页面报错如下：
> Refused to apply style from 'http://localhost:8080/static/layui/css/layui.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.


静态资源是可以随意放置的。因为webpack就是做资源的依赖分析，然后帮你做各种处理，最终输出。

你这个报错的话，好像不是静态资源导致的错误。建议往其他方向去排查一下。
