### ISSUE TITLE
大佬！html文件无法热更新~~

### ISSUE THREAD

**Issue by zzzzzzcc** [JesseZhao1990/multipage-webpack-scaffolding#14]
我测试了下，发现html无法热更新，css和js都是可以的，
还有就是没有说明文档，比如大佬更新了的不打包html文件功能我也不知道怎么配置（虽然我没用到）.....
果然还是我太菜了么................

**Comment by zzzzzzcc** [comment]
我去网上查了如何html热更新，但是搞不定................

**Comment by JesseZhao1990** [comment]
> 我去网上查了如何html热更新，但是搞不定................

已支持。https://github.com/JesseZhao1990/multipage-webpack-scaffolding/commit/a21e1ce698ce48dc649899925e40275b48950f54
