### ISSUE TITLE
build  无法打包css 文件

### ISSUE THREAD

**Issue by Shijf** [JesseZhao1990/multipage-webpack-scaffolding#17]
build  无法打包css 文件

**Comment by haue** [comment]
是啊，作者也不测试一下

**Comment by JesseZhao1990** [comment]
@Shijf @haue 提供一下更详细的信息。我来看一下

**Comment by JesseZhao1990** [comment]
@Shijf @haue 按道理来讲，只要你在你的文件里引用了对应的css，webpack的style-loader就会把其插入到对应的HTML中，我怀疑是不是你们没有import 对应的css

**Comment by haue** [comment]
@JesseZhao1990 就你这个下载之后什么都不改，build后打开，你那里首页的“css测试”是红色的吗？

**Comment by haue** [comment]
@JesseZhao1990 dev是没问题的，build后css都失效了。

**Comment by haue** [comment]
@JesseZhao1990 你那边正常吗？

**Comment by JesseZhao1990** [comment]
@haue 刚刚验证了一下，确实是有这个问题，问题已修复。
