### ISSUE TITLE
使用jquery的时候build有问题

### ISSUE THREAD

**Issue by haue** [JesseZhao1990/multipage-webpack-scaffolding#18]
```
import $ from "jquery";
console.log(1)
```
上面的代码，在dev下是正常的，控制台输出1
但是build后的代码什么也没有

**Comment by JesseZhao1990** [comment]
@haue webpack在production模式会优化代码，压缩、去掉console等，具体的信息查阅webpack文档：https://webpack.js.org/configuration/mode/#mode-production

如果实在不想让其去掉console，或者是只去掉console.log, 保留console.info 等，都可以灵活配置，详细的文档： https://webpack.js.org/plugins/terser-webpack-plugin/#root

最佳实践是生产环境不需要在控制台乱输出内容，可能会带来内存泄露等问题。

**Comment by JesseZhao1990** [comment]
![image](https://user-images.githubusercontent.com/15058550/76434585-d54b3c80-63f0-11ea-8f29-59010f09d05d.png)

**Comment by haue** [comment]
可能我上面举的例子不太恰当，不能用console.log，但是换做alert('xxxx')，alert语句也是不会执行，很奇怪。
把
```
import $ from "jquery";
```
去掉就可以。当然前提我install了jquery，你在引入jquery的时候就没有问题吗？

**Comment by haue** [comment]
什么原因？

**Comment by JesseZhao1990** [comment]
@haue 已修复
