### ISSUE TITLE
build 之后about页面图片显示不出来

### ISSUE THREAD

**Issue by 0xlc** [JesseZhao1990/multipage-webpack-scaffolding#19]

**Comment by JesseZhao1990** [comment]
@aliuchuang 我这边测的没问题啊。拉一下最新的代码。重新build一下。

**Comment by 0xlc** [comment]
它好像可以了 感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JesseZhao1990"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 晚上11:16
收件人:&nbsp;"JesseZhao1990/multipage-webpack-scaffolding"<multipage-webpack-scaffolding@noreply.github.com&gt;;
抄送:&nbsp;"God people"<487699978@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JesseZhao1990/multipage-webpack-scaffolding] build 之后about页面图片显示不出来 (#19)





 
@aliuchuang 我这边测的没问题啊。拉一下最新的代码。重新build一下。
