### ISSUE TITLE
请问image/media的路径如何来写？

### ISSUE THREAD

**Issue by sandmanman** [JesseZhao1990/multipage-webpack-scaffolding#3]

**Comment by JesseZhao1990** [comment]
@sandmanman 因为webpack中已经定义了图片路径的转换问题。所以，不用担心在开发时图片能使用，build之后图片资源无法加载的问题。关于图片的路径的书写，我举两个例子，仅供参考

#### 1. 如果是在html中引用，就直接用相对路径,在示例中的about页面，有图片资源的引用，可参考

```
<img src="../../images/cat.jpeg"/>
```

#### 2. 在js中使用，也是使用相对路径。如下所示

```
import imgUrl from '../../images/cat.jpeg';
const img = document.createElement("img");
img.style.width = "200px";
img.src = imgUrl;
document.body.appendChild(img);

```

**Comment by sandmanman** [comment]
@JesseZhao1990 非常感谢您的回复。
如果是video标签
`<video src="../media/heng.mp4" poster="../images/poster2.jpg" style="object-fit:fill"></video>`
是不是就得使用js的方法来搞定了？
再次打扰。

**Comment by JesseZhao1990** [comment]
@sandmanman video的路径的写法和图片是一样的。两种方法都是可以的。
