### ISSUE TITLE
请问怎么把项目配置中的less替换成scss

### ISSUE THREAD

**Issue by huangyangteng** [JesseZhao1990/multipage-webpack-scaffolding#6]
1. 我在配置文件中的module中添加了对.scss文件的处理，但是并不生效
2. 项目中没有.less文件就会报错
项目中对less文件的处理有less-loader和ExtractTextPlugin插件，还有没有其他配置导致项目必须依赖less的？

**Comment by JesseZhao1990** [comment]
@huangyangteng  如果不喜欢less，换成sass的方法如下所示

![image](https://user-images.githubusercontent.com/15058550/43676338-bd294274-9821-11e8-8010-5a21b00ac336.png)

我已经将配置改好了，你可以拉取代码，切换到`sass`分支体验
