### ISSUE TITLE
npm run dev 报错啊

### ISSUE THREAD

**Issue by xlx111** [JesseZhao1990/multipage-webpack-scaffolding#7]
报错信息：
\multipage-webpack-scaffolding-master\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined

**Comment by xlx111** [comment]
已

**Comment by xlx111** [comment]
已解决，重新安装了webpack-cli就好了

**Comment by JesseZhao1990** [comment]
@xlx111 是的。这是一个webpack-cli的bug。升级webpack-cli到版本3.1.1即可解决。
https://github.com/webpack/webpack/issues/8082

**Comment by xlx111** [comment]
嗯嗯，谢谢



------------------ 原始邮件 ------------------
发件人: "JesseZhao1990"<notifications@github.com>;
发送时间: 2018年9月26日(星期三) 下午4:25
收件人: "JesseZhao1990/multipage-webpack-scaffolding"<multipage-webpack-scaffolding@noreply.github.com>;
抄送: "you"<331741294@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [JesseZhao1990/multipage-webpack-scaffolding] npm run dev 报错啊 (#7)




@xlx111 是的。这是一个webpack-cli的bug。升级webpack-cli到版本3.1.1即可解决。
 webpack/webpack#8082
